### ISSUE TITLE
Unknown property names

### ISSUE THREAD

**Issue by cyberjoac** [peterbe/premailer#103]
Property: Unknown Property name. [31:17: -ms-interpolation-mode]
Property: Unknown Property name. [4:17: mso-line-height-rule]
Property: Unknown Property name. [106:17: -webkit-text-size-adjust]
Property: Unknown Property name. [107:17: -ms-text-size-adjust]
Property: Unknown Property name. [188:21: text-rendering]
Property: Unknown Property name. [613:17: mso-text-raise]
Property: Unknown Property name. [624:17: transition]
Property: Unknown Property name.

I'm not sure what is this and what can I do about that..
Thanks for any help!

**Comment by peterbe** [comment]
You mean when you run the nosetests?

**Comment by cyberjoac** [comment]
No, when running the transform function on an HTML page with those
properties...
I believe they have to do with some properties that are barely used
(cross-compatibility issues and stuff...)

**Comment by peterbe** [comment]
I think it's an output from cssselect and there's not much you can do about
it.


On Mon, Jan 5, 2015 at 11:39 AM, cyberjoac <notifications@github.com> wrote:

> No, when running the transform function on an HTML page with those
> properties...
> I believe they have to do with some properties that are barely used
> (cross-compatibility issues and stuff...)
>
> On Mon, Jan 5, 2015 at 5:40 PM, Peter Bengtsson <notifications@github.com>
>
> wrote:
>
> > You mean when you run the nosetests?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/peterbe/premailer/issues/103#issuecomment-68724984>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/peterbe/premailer/issues/103#issuecomment-68734707>.
>



-- 
Peter Bengtsson
Mozilla Web Engineering

**Comment by texuf** [comment]
Would it be possible to add macros for these properties? I'm running into this issue as well.

**Comment by peterbe** [comment]
@texuf What's a "macro"?

**Comment by texuf** [comment]
Excellent point! This error gets logged from cssutils/css/property.py, which is not in your project. Looks like the fix would be there. Anyone familiar with this repo?

**Comment by texuf** [comment]
I came up with a hack to get rid of these warnings if anyone is interested. Just call this before you call any premailer functions - https://gist.github.com/texuf/1e1ef7fce7aaa67caf4d

feel free to add the extra properties you need.
