### ISSUE TITLE
What is this if doing

### ISSUE THREAD

**Issue by vanng822** [peterbe/premailer#111]
Can someone, more involved, take a look on this one. Either I am blind or the condition not making sense

https://github.com/peterbe/premailer/blob/master/premailer/premailer.py#L490

**Comment by peterbe** [comment]
Yeah, that makes no sense. 

For the record, the permalink to that line is: https://github.com/peterbe/premailer/blob/e1a9a42f6ba19f06e58506fbb4013865fd358e77/premailer/premailer.py#L490

It seems like a typo that was never caught in a unit test. I think that code was written in [2009](https://github.com/peterbe/premailer/commit/c4f2634a99fc5005011ffde54ae0336ea1497ef5) (6 years ago!!) and I think the intention there was to make sure the `{` and `}` were balanced. 

Would you mind making a PR to make it compare the count of `{` with the count of `}`?

**Comment by vanng822** [comment]
Ok, it just simple thing. Maybe you just fix it directly?

**Comment by vanng822** [comment]
Great!
