### ISSUE TITLE
Broken under Python 3.5

### ISSUE THREAD

**Issue by juokaz** [peterbe/premailer#137]
cssutils is broken under Python 3.5 (cssutils issue [here](https://bitbucket.org/cthedot/cssutils/issues/52/bad-octal-escape-blows-up-on-python-35b3)). Which also makes premailer fail.

Don't have an idea how this could be addressed. 

    /usr/local/lib/python3.5/site-packages/premailer/__init__.py:2: in <module>
        from .premailer import Premailer, transform
    /usr/local/lib/python3.5/site-packages/premailer/premailer.py:32: in <module>
        import cssutils
    /usr/local/lib/python3.5/site-packages/cssutils/__init__.py:123: in <module>
        profile = Profiles(log=log)
    /usr/local/lib/python3.5/site-packages/cssutils/profiles.py:188: in __init__
        macros[self.CSS3_TEXT]
    /usr/local/lib/python3.5/site-packages/cssutils/profiles.py:291: in addProfiles
        self.addProfile(profile, properties.copy(), None)
    /usr/local/lib/python3.5/site-packages/cssutils/profiles.py:340: in addProfile
        self._profilesProperties[profile] = self._compile_regexes(properties)
    /usr/local/lib/python3.5/site-packages/cssutils/profiles.py:214: in _compile_regexes
        value = re.compile('^(?:%s)$' % value, re.I).match
    /usr/local/lib/python3.5/re.py:224: in compile
        return _compile(pattern, flags)
    /usr/local/lib/python3.5/re.py:293: in _compile
        p = sre_compile.compile(pattern, flags)
    /usr/local/lib/python3.5/sre_compile.py:536: in compile
        p = sre_parse.parse(p, flags)
    /usr/local/lib/python3.5/sre_parse.py:829: in parse
        p = _parse_sub(source, pattern, 0)
    /usr/local/lib/python3.5/sre_parse.py:437: in _parse_sub
        itemsappend(_parse(source, state))
    /usr/local/lib/python3.5/sre_parse.py:778: in _parse
        p = _parse_sub(source, state)
    /usr/local/lib/python3.5/sre_parse.py:437: in _parse_sub
        itemsappend(_parse(source, state))
    /usr/local/lib/python3.5/sre_parse.py:778: in _parse
        p = _parse_sub(source, state)
    /usr/local/lib/python3.5/sre_parse.py:437: in _parse_sub
        itemsappend(_parse(source, state))
    /usr/local/lib/python3.5/sre_parse.py:778: in _parse
        p = _parse_sub(source, state)
    /usr/local/lib/python3.5/sre_parse.py:437: in _parse_sub
        itemsappend(_parse(source, state))
    /usr/local/lib/python3.5/sre_parse.py:778: in _parse
        p = _parse_sub(source, state)
    /usr/local/lib/python3.5/sre_parse.py:437: in _parse_sub
        itemsappend(_parse(source, state))
    /usr/local/lib/python3.5/sre_parse.py:778: in _parse
        p = _parse_sub(source, state)
    /usr/local/lib/python3.5/sre_parse.py:437: in _parse_sub
        itemsappend(_parse(source, state))
    /usr/local/lib/python3.5/sre_parse.py:778: in _parse
        p = _parse_sub(source, state)
    /usr/local/lib/python3.5/sre_parse.py:437: in _parse_sub
        itemsappend(_parse(source, state))
    /usr/local/lib/python3.5/sre_parse.py:565: in _parse
        code2 = _class_escape(source, that)
    /usr/local/lib/python3.5/sre_parse.py:348: in _class_escape
        'range 0-0o377' % escape, len(escape))
    sre_constants.error: octal escape value \777 outside of range 0-0o377 at position 93

**Comment by peterbe** [comment]
Thanks for filing. Let's hope the cssutils people crack it soon enough.

**Comment by cthedot** [comment]
Actually there is no people but mainly me and not even that I fear. Please see the bug request on cssutils.

**Comment by bameda** [comment]
This is the fix for cssutils https://bitbucket.org/cthedot/cssutils/pull-requests/15/fix-octal-escape-on-python-35 but the author of cssutils say he is currently not maintaining the lib. 

![image](https://cloud.githubusercontent.com/assets/877218/10308214/75cafde4-6c34-11e5-9da3-044bd11c821a.png)

So... what can we do?

**Comment by bameda** [comment]
I'll try to make a "pretty monkey patch" temporarily, but we have to find a better solution.

**Comment by thelok** [comment]
I'm not part of this project but I encountered the same error and was searching on the internet for a fix to this... The workaround in https://bitbucket.org/cthedot/cssutils/pull-requests/15/fix-octal-escape-on-python-35 seems to have worked for me and fixed my issue.

**Comment by peterbe** [comment]
@thelok What would really help @cthedot is that you mention that as a comment on that bitbucket pull request. He doesn't maintain that project any more but if multiple people say it works he might be confident to merge it and push out a release.

**Comment by cthedot** [comment]
Maybe I have some time this week as I am "on vacation" and already come out as a dick ;)

But is there any way to let other people make releases to Pypi or elsewhere? I merged the pull request but actually have not even Python installed on my machine (did a clean OS update some months ago). So I'd need to install Python(s), download the repo and try to make packages and publish them which may even work this time but is not what people deserve who use the lib. 
If anyone already did the appropriate packages (including running the tests etc) and let me have them I could simply upload them on Pypi. Giving write rights on bitbucket should be easy too so downloads there would be possible for anyone interested. Is there anyone interested? 
And sorry again for being so hesitant but as I like to let live on a lib I invested time in over 10 years I have not used it in some years either...

**Comment by peterbe** [comment]
@cthedot you need to sign in to pypi to grant someone else that access. Sign in to [https://pypi.python.org/](https://pypi.python.org/pypi/) click on your [package page](https://pypi.python.org/pypi/cssutils/) and near the top there should be a "Roles" link. Once you're in there you can add other users. You need to know their username on pypi. I don't know who https://bitbucket.org/Dunj3/ is but if you want to share it with me it's `peterbe`. 

Then, that other person can execute the `python setup.py sdist bdist_wheel upload` command.

**Comment by cthedot** [comment]
@peterbe great, thanks a lot for the explanation, I did add you as maintainer, hope this helps. If you need anything more please let me know!

**Comment by juokaz** [comment]
@peterbe I tested this again and the current cssutils release no longer has this problem.

I'm closing this as resolved.
