### ISSUE TITLE
Add support for change location <style> tag

### ISSUE THREAD

**Issue by rash2x** [peterbe/premailer#149]
If we send email with <style> tag in <head> email application don't be use this styles.
We need to add support for changing the location of a <style> tag in body or head

**Comment by peterbe** [comment]
I don't understand your description at all. Why would you ever want to have the `<style>` tag in any other place than the `<head>`?

**Comment by rash2x** [comment]
because if we send letter in gmail, we see page without css.

**Comment by rash2x** [comment]
i was wrong, all okay

**Comment by peterbe** [comment]
no problem
