### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by toxinu** [peterbe/premailer#168]
Is it possible to maintain a change log please? :smiley_cat:

**Comment by peterbe** [comment]
That would be nice indeed but sadly it hasn't been kept. 
Is there some sort of software as a service that can figure that out for you?

**Comment by socketubs** [comment]
@peterbe, I don't know. But maybe a change log at least for backwards incompatible changes?

**Comment by peterbe** [comment]
backwards incompatible changes are basically changes related to the major version number incrementing.

**Comment by socketubs** [comment]
Of course, I know semantic versioning but it's always hard to find which change break your code.
This is the purpose of a change log.

**Comment by peterbe** [comment]
I'm not disagreeing that a changelog would be ten times better than any automated "botlog", which we don't even have. 
The motivation to work on it is hard though. This project has had 40 contributors over the years and most people come and go and have this patches/needs resolved. It's not big enough to be a community.

**Comment by socketubs** [comment]
No problem. I understand, I just said that as a little reminder. :smile: 
I don't ask to have a change log of previous releases, but just trying to have it for next changes if possible.

And by the way, thank you for doing premailer.

**Comment by Daenyth** [comment]
A list of specific breaking changes would be a huge boon. I have a project I inherited using premailer 1.x, which doesn't support python3, and I have no clue what I might break if I update. I'm especially afraid of changes that would silently not crash but produce different results.

**Comment by adamzap** [comment]
@peterbe Congrats on the `v3.3.0` release! Is there a list of changes posted anywhere? I'm having trouble finding one. Thanks!

**Comment by peterbe** [comment]
> Is there a list of changes posted anywhere? 

I'm sad to say there is not :(

That's what this issue is about. I'm unlikely to find the motivation to start one. Since I don't use this library for any of my projects any more I use the little energy I can afford to spend on it to just review pull requests.

**Comment by adamzap** [comment]
Fair enough. I know how you feel!

**Comment by adamzap** [comment]
Looks like this can be closed as of 67713eaa, thanks @peterbe!
