### ISSUE TITLE
tag releases on github

### ISSUE THREAD

**Issue by ignatenkobrain** [peterbe/premailer#175]
Would be nice if you will start doing that as it will simplify packaging for distros.

**Comment by peterbe** [comment]
Why not just use the releases on PyPI?

**Comment by ignatenkobrain** [comment]
Because those are not real releases. It does not include all files which we have in git.

**Comment by peterbe** [comment]
That's odd. If some files don't go into the wheel/tarball, isn't there a reason for that? For example, why do you need `.gitignore` etc. in the distros?

**Comment by ignatenkobrain** [comment]
I didn't check tarball as I'm FAQ away from laptop, but I suppose there is missing coveragerc, tox.ini

**Comment by peterbe** [comment]
Sorry but I don't agree. The files that aren't shipping in pypi aren't meant for putting in distros. Having to make a tag as well as a release is more work that necessary which isn't worth it for a side-project, like this, where I want to keep things as simple as possible.

**Comment by ignatenkobrain** [comment]
what can be easier than doing:
```
$ git tag 3.0.1 2d096e9f668313c8570dddc43bbd47eead476117
$ git push origin 3.0.1
```
?

**Comment by MartinBriza** [comment]
Please reconsider this. It's just two commands (really, there's no more work to it) and it helps distribution packaging tremendously.

**Comment by peterbe** [comment]
It's yet another thing to have to do. 
I just still don't get why you would want to ship development artifacts.

**Comment by ignatenkobrain** [comment]
There is .coveragerc. When I package I try to make coverage as well.
