### ISSUE TITLE
Coda 2 plugin flavor?

### ISSUE THREAD

**Issue by amaisano** [peterbe/premailer#178]
Would absolutely love this as a plugin in Coda 2. Any possibility of that?

**Comment by peterbe** [comment]
What is Coda 2?

**Comment by amaisano** [comment]
https://panic.com/coda/plugins.php#Plugins

 
 
Adamo Maisano  DESIGNER | DEVELOPER
Cleveland  DESIGN | INTERACTIVE | BRANDING
NEW Phone: 617.471.4641 x11 • Fax: 617.471.4646
www.clevelanddesign.com <http://www.clevelanddesign.com/about/our-team/Adamo>

**Comment by peterbe** [comment]
I haven't used php since 2001 but I can't imagine that php can integrate python code in run-time, right? So you'd have to wrap premailer and execute it in a sub process on the command line. 
Either way, that'd be up to the author of that coda plugin. Not something that could go into premailer.
