### ISSUE TITLE
Transform breaks escaping

### ISSUE THREAD

**Issue by whatisjasongoldstein** [peterbe/premailer#187]
We're using premailer to inline CSS. It also does some weird stuff like convert

```
<meta name="tag" content="Hello &quote;world!&quote;">
```

to

```
<meta name="tag" content='Hello "world!"'>
```

While that's valid HTML, other pieces of our ecosystem aren't expecting it. Can it be an optional parameter or something else I can disable?

Thanks

**Comment by peterbe** [comment]
I honestly don't know and it's unlikely that I'll find the time to find out. `premailer` heavily depends and relies on how `lxml` works. Best option would be to search there for solutions and then we can "port" that into premailer.

**Comment by whatisjasongoldstein** [comment]
Not a problem. I spent a little time seeing if I can make lxml do it. Since this is pretty esoteric, perfectly valid HTML, it's not worth anyone going down the rabbit hole for. Thanks!
