### ISSUE TITLE
Fonts are falling back

### ISSUE THREAD

**Issue by ghost** [peterbe/premailer#194]
Importing fonts as so:
```
@font-face {
  font-family: 'Lato';
  src: asset-url('Lato-Regular.eot');
  src: asset-url('Lato-Regular.eot?#iefix') format('embedded-opentype'),
        asset-url('Lato-Regular.woff') format('woff'),
        asset-url('Lato-Regular.ttf') format('truetype');
}

html, body {
  font-family: 'Lato', 'Helvetica Neue', Helvetica, Arial, sans-serif;
  font-size: 14px;
}

```

The font shows up before the email is sent, when looking at the HTML file, however, when viewing the email in a client after it has been sent, the font falls back to Arial. I have tried both Apple Mail and Gmail. The font shows up in Apple mail if premailer is skipped.

I am using the rails version, I have tried it with the flag: `preserve_styles: true`

**Comment by peterbe** [comment]
"I am using the rails version"?? What does that mean?

Are you sure the `<style>` tag that is preserved has absolute URLs to the fonts?

**Comment by p12tic** [comment]
@peterbe: I think this issue can be closed.
