### ISSUE TITLE
Premailer tries download css 

### ISSUE THREAD

**Issue by TZanke** [peterbe/premailer#207]
Hello,

in our customer environments, internet access is not allowed, but Premailer tries to download css files and encounters an exception. I could no find any option to disable this feature.

```
File "premailer/premailer.py", line 341, in transform  
    css_body = self._load_external(href)

File "premailer/premailer.py", line 520, in _load_external
    css_body = self._load_external_url(url)

File "premailer/premailer.py", line 507, in _load_external_url
    return requests.get(url).text

File "requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)

File "requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)

File "requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)

File "requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)

File "requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)

ConnectionError: HTTPSConnectionPool(host='fonts.googleapis.com', port=443): Max retries exceeded with url: /css?family=Open+Sans:300,400,600,700 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fe912dcec10>: Failed to establish a new connection: [Errno 101] Das Netzwerk ist nicht erreichbar',))
```

**Comment by peterbe** [comment]
Is it possible that you have something like this:

```html
<html>
<head>
<link rel="stylesheet" href="https://fonts.googleapis.com?family=Lato">
<style>
css { key: value }
</style>
<body>
  ...
</body>
</html>
```

In that case, try setting the `data-premailer="ignore"` attribute onto that `<link>` tag.

**Comment by TZanke** [comment]
This is correct. Cause we are using Premailer to generate the reply Blockquote, the source mail is from external sources. Adding a ignore attribute comes at same cost as removing the entire tag.

**Comment by peterbe** [comment]
But if you put an ignore tag on the font stylesheet, doesn't that solve your problem? Or do you have a stylesheet that uses `@import externalURL`?

**Comment by TZanke** [comment]
`data-premailer="ignore"` works as expected. But in both cases i have to manipulate external first. Would be nice to have a Premailer parameter which disables external loading at all.

**Comment by peterbe** [comment]
Ah! Like an option that says "Don't ever bother doing any more downloads when you process this."
Yeah, that shouldn't be too hard. I won't make such a patch but I'd be more than willing to assist you in making the pull request.

**Comment by TZanke** [comment]
I added a pull request. Please review.

In my opinion `skip_load_external` should be True by default.
