### ISSUE TITLE
will premailer be able to process included style sheets (<link rel="stylesheet"...)?

### ISSUE THREAD

**Issue by woodz-** [peterbe/premailer#216]
Just a question,

I'd like to go one step further. Instead of embedding the styles directly into html files, it's much more practical to just link (include) them into html files as this is the standard on most web projects for my understanding.

Then premailer would need to be able to resolve the link in the first step pointing to a css file and read the content from that destination, then modify the source html file (inline the css).
Would that be possible this time? Are there any samples out?

**Comment by peterbe** [comment]
It can do this already. As a side-note; in [this PR](https://github.com/peterbe/premailer/pull/214) it will become a feature to NOT process external links.
