### ISSUE TITLE
Reusing premailer instances does not work

### ISSUE THREAD

**Issue by viernullvier** [peterbe/premailer#217]
The README contains a [nice section](https://github.com/peterbe/premailer#if-execution-speed-is-on-your-mind) on speeding up premailer by reusing premailer instances. This, however, [throws an exception](https://github.com/peterbe/premailer/blob/master/premailer/premailer.py#L319) on subsequent iterations because the instance's internal `html` attribute was already set on the first iteration.

Possible solutions:
 **a)** Refactor code to allow for multiple runs
 **b)** Remove problematic section from documentation

**Comment by peterbe** [comment]
Wow! That's a good catch. Would you mind attacking point a) so we can "fail forward"?

**Comment by viernullvier** [comment]
I've just had a look at the code. As far as I can see, there was no specific reason to rely on `self.html` so I've refactored `transform()` to just use its own `html` argument (and fall back to `self.html` in case it's not given).

**Comment by shanon-equityzen** [comment]
:clap: as I just noticed this same issue.   The latest via pip (v3.3.0) does not contain this fix.  Can you please advise when it'll be released?   thanks!

**Comment by peterbe** [comment]
For the record, @shanon-equityzen and I are discussing the release process here: https://github.com/peterbe/premailer/pull/218#issuecomment-471543169
