### ISSUE TITLE
New lxml version doesn't include cssselect

### ISSUE THREAD

**Issue by fim** [peterbe/premailer#22]
Newly released lxml version (3.0.alpha2) which gets pulled automatically by `pip install premailer` doesn't come with cssselect bundled in the package but it is now a separate package. This throws import errors at runtime when trying to import anything from cssselect since it's not installed.

```python
>>> from premailer import Premailer, transform, __version__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/foo2/lib/python2.7/site-packages/premailer/__init__.py", line 1, in <module>
    from premailer import Premailer, transform, __version__
  File "/tmp/foo2/lib/python2.7/site-packages/premailer/premailer.py", line 3, in <module>
    from lxml.cssselect import CSSSelector
  File "/tmp/foo2/lib/python2.7/site-packages/lxml/cssselect.py", line 18, in <module>
    raise ImportError('cssselect seems not to be installed. '
ImportError: cssselect seems not to be installed. See http://packages.python.org/cssselect/
```
After doing a pip install cssselect

```python
>>> from premailer import Premailer, transform, __version__
>>> 
```

Related lxml thread is here: https://github.com/lxml/lxml/pull/46

**Comment by peterbe** [comment]
`cssselect` is its own dependent requirement.
https://github.com/peterbe/premailer/blob/99603f08da033d5a02503ea999566a9234ad876a/setup.py#L41
