### ISSUE TITLE
Modify text formatting

### ISSUE THREAD

**Issue by rbq** [peterbe/premailer#226]
I couldn't find any information about how to modify the HTML-to-text conversion. Are there any hooks or an interface for a pluggable backend?

I'd really like to change the link formatting to something more common (`Text ( URL )` → `Text <URL>`) and try to remove some extra line breaks I get within list items containing links.

**Comment by peterbe** [comment]
I don't think that exists. Do you mean passing a callback or something? Because that would be neat.
You might want to start with looking at what's natively possible with lxml. Like, can you hook into the pretty_print function or something like that.

**Comment by rbq** [comment]
Ooops, this is not the Ruby premailer gem, is it? >.< Sorry about that.
