### ISSUE TITLE
Style sorting breaking proper precedence

### ISSUE THREAD

**Issue by jack-guy** [peterbe/premailer#260]
For the following styles:
```
.foo {
  padding-left: 6px;
  padding-right: 6px;
  padding-top: 8px;
  padding-bottom: 8px;
  padding: 4px;
}
```
The browser should see the padding rules as all having the same precedence. As a tie-breaker, whichever appears last in the list applies (in this case `padding: 4px`).

Premailer appears to be [sorting styles alphabetically in `csstext_to_pairs`](https://github.com/peterbe/premailer/blob/9cbd27afa4fa81bb84219d091e391ef4e7109fe0/premailer/merge_style.py#L25). This causes the `padding` rule to appear before the others and breaks the precedence. 

Is there any reason to be sorting styles in this way? Would you be open to a PR removing this sort?

```
> /virtualenv_run/lib/python3.7/site-packages/premailer/premailer.py(473)transform()
-> for item in items:
(Pdb) style
'font-family:"Open Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;font-weight:normal;font-size:14px;line-height:20px;color:rgba(43, 39, 60, 1);text-align:left;margin-bottom:16px;padding-left:6px;padding-right:6px;padding-top:8px;padding-bottom:8px;padding:5px'
(Pdb) processed_style
[('color', 'rgba(43, 39, 60, 1)'), ('font-family', '"Open Sans", "Helvetica Neue", Helvetica, Arial, sans-serif'), ('font-size', '14px'), ('font-weight', 'normal'), ('line-height', '20px'), ('margin-bottom', '16px'), ('padding', '5px'), ('padding-bottom', '8px'), ('padding-left', '6px'), ('padding-right', '6px'), ('padding-top', '8px'), ('text-align', 'left')]
```

**Comment by peterbe** [comment]
I have no idea/memory why it sorts them. Seems odd. Try removing it and see if the tests break. 
Also, perhaps you should add a test that uses that great example of `padding-left: ....; padding: ...` to assert that `output.find('padding:') > output.find('padding-left:')` or something. 
Go for it!

**Comment by jack-guy** [comment]
@peterbe thanks for the quick response! Opened https://github.com/peterbe/premailer/pull/261 - if you're able to merge / release this change that would be a big help to me!

Cheers

**Comment by peterbe** [comment]
>  if you're able to merge / release this change that would be a big help to me!

I'll say it now so I don't forget. Please remind me to kick off a release once this is merged. Just in case I forget.
