### ISSUE TITLE
keep class attributes

### ISSUE THREAD

**Issue by ColorfullyTyler** [peterbe/premailer#33]
the transform() function replaces the "class" attribute with the appropriate styling, but it also removes the class from the html elements. I need the styling added inline, but the classes to be left within their elements so that my @media (!important) styling can be inserted in after and still have classes to point to within the dom.

Im having a hard time changing your code to meet this needs, do you have any thoughts on how I could keep the classes within the html elements but still inject the inline styling?

**Comment by sethlivingston** [comment]
I need this, too, and I'm wondering how others are getting by without it.

**Comment by sethlivingston** [comment]
Whew, this is an option.

    inlined_html = premailer.Premailer(plain_html, remove_classes=False).transform()

See `premailer.py` for additional options. It appears that some of them are defaulted one way for the console app and another way for the API.

**Comment by peterbe** [comment]
What do you think, should [the default](https://github.com/peterbe/premailer/blob/cc18022e334d5336e48f75bd4e0a73c98cc5942a/premailer/premailer.py#L124) be switched to `False` by default?

**Comment by sethlivingston** [comment]
Personally I do, because those class names are key in media queries. I'm
just one guy, though. :) The fact that it's configurable makes it all good
for me.

**Comment by peterbe** [comment]
What do you think @ccorcos @mpj17 @lavr @dbarbar @graingert @vanng822 @elidickinson 
Should it be the *default* to keep the `class` attributes in the output HTML?

**Comment by graingert** [comment]
IMHOP, should default to keep the class attributes

**Comment by mpj17** [comment]
I think that keeping the `class` attribute will be less confusing for new people, especially as some `@media` hacks require the classes to be there. Sadly, changing defaults is always a challenge.

For what it is worth, [I explicitly keep the class attributes](https://github.com/groupserver/gs.content.email.base/blob/master/gs/content/email/base/emailmessage.py#L146) in GroupServer.

**Comment by graingert** [comment]
Swap the default, then bump the major version?

**Comment by mpj17** [comment]
By strict [semantic versioning](http://semver.org/) it will be an incompatible version change, so it will be a major-number bump. However, that is for @peterbe to decide `;)`

**Comment by vanng822** [comment]
For me I don't see much gain vs people have to change their code but if it helps people then swap and I agree about major version.

**Comment by graingert** [comment]
To be honest people probably won't need to change their code, as they are
not depending on the class not being there.
On 7 Jun 2016 7:11 am, "Nguyen Van Nhu" <notifications@github.com> wrote:

For me I don't see much gain vs people have to change their code but if it
helps people then swap and I agree about major version.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/peterbe/premailer/issues/33#issuecomment-224188670>,
or mute
the thread
<https://github.com/notifications/unsubscribe/AAZQTMIwEA_wfPE0CmJHwBqP7CMgRij5ks5qJQt5gaJpZM4Ao96V>
.

**Comment by ccorcos** [comment]
Apple Mail client allows media queries. So I leave style tags and classes.
This would probably be a sane default.

**Comment by peterbe** [comment]
See https://github.com/peterbe/premailer/pull/167

I'll blog about it more later.

**Comment by peterbe** [comment]
[Blog post here](https://www.peterbe.com/plog/premailer-3.0.0)
